### PR TITLE
Bump request and xhr versions

### PR DESCRIPTION
**Pull request by derekr**
Fixes some custom header issues I’m having

### CODE REVIEW

**Comment by zeke** [comment]
Would you say minor version bumps in the deps == minor bump in nets?

**Comment by derekr** [comment]
Not sure. Assuming the API of xhr is up to date w/ requests I think the version bumping should match. So yeah minor dep, minor nets :D.

**Comment by zeke** [comment]
Thanks! Landed in 3.2.0

**Comment by derekr** [comment]
:boom: thanks for the quick publish!

**Pull request merged**
